name: Deploy Application

on:
  push:
    branches:
      - main  # Runs when pushing to the main branch

jobs:
  deploy:
    runs-on: ${{ matrix.os }}  # Runs on multiple OS

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # Run on Linux, Windows & macOS

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Environment Variables
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: |
          echo "✅ Environment variables loaded from GitHub Secrets."
          echo "Using DJANGO_SECRET_KEY (hidden for security)"
          echo "Using NEWS_API_KEY (hidden for security)"
          echo "Using WEATHER_API_KEY (hidden for security)"

      - name: Deploy Application
        run: echo "🚀 Deployment completed on ${{ matrix.os }}"
