name: Deploy Application

on:
  push:
    branches:
      - main  # Runs when pushing to the main branch

jobs:
  deploy:
    runs-on: ${{ matrix.os }}  # Runs on multiple OS

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # Run on Linux, Windows & macOS

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check Environment Variables (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          if [ -z "$DJANGO_SECRET_KEY" ]; then 
            echo "❌ DJANGO_SECRET_KEY is missing!"; 
            exit 1; 
          fi
          if [ -z "$NEWS_API_KEY" ]; then 
            echo "❌ NEWS_API_KEY is missing!"; 
            exit 1; 
          fi
          if [ -z "$WEATHER_API_KEY" ]; then 
            echo "❌ WEATHER_API_KEY is missing!"; 
            exit 1; 
          fi
          echo "✅ All required secrets are set."

      - name: Check Environment Variables (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          if (-not $env:DJANGO_SECRET_KEY) { 
            Write-Error "❌ DJANGO_SECRET_KEY is missing!"
            exit 1
          }
          if (-not $env:NEWS_API_KEY) { 
            Write-Error "❌ NEWS_API_KEY is missing!"
            exit 1
          }
          if (-not $env:WEATHER_API_KEY) { 
            Write-Error "❌ WEATHER_API_KEY is missing!"
            exit 1
          }
          Write-Host "✅ All required secrets are set."

      - name: Deploy Application
        run: echo "Deployment completed on ${{ matrix.os }}"
